# Generated by Django 3.1.4 on 2021-11-25 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RestaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_no', models.IntegerField(unique=True)),
                ('bot_name', models.CharField(max_length=300, unique=True)),
                ('bot_color', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='bot_images')),
                ('status', models.BooleanField(default=True, help_text='bot working(active or inactive)')),
                ('avialable', models.BooleanField(default=True, help_text='available or not avialabe for delivery')),
                ('ip', models.CharField(max_length=15)),
                ('port', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.restaurant')),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
                'ordering': ('-id',),
            },
        ),
    ]
