# Generated by Django 3.1.4 on 2021-11-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotsApp', '0002_bot_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_no',
            field=models.IntegerField(),
        ),
    ]
