# Generated by Django 3.1.4 on 2021-12-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotsApp', '0005_auto_20211213_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_name',
            field=models.CharField(max_length=300),
        ),
    ]
