# Generated by Django 3.1.4 on 2021-11-25 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('restaurant', models.CharField(max_length=300)),
                ('bot_no', models.IntegerField()),
                ('bot_name', models.CharField(max_length=100)),
                ('table_no', models.IntegerField()),
                ('ip', models.CharField(max_length=30)),
                ('port', models.IntegerField()),
                ('food_type', models.CharField(max_length=30)),
                ('speed_of_the_bot', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_delivered', models.BooleanField(default=False)),
                ('time', models.DecimalField(decimal_places=6, default=0, max_digits=50)),
            ],
            options={
                'verbose_name': 'Final Delivery',
                'verbose_name_plural': 'Final Deliveries',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=300, unique=True)),
                ('rest_location', models.CharField(max_length=300)),
                ('rest_logo', models.ImageField(upload_to='logos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TempDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('restaurant', models.CharField(max_length=300)),
                ('bot_name', models.CharField(max_length=300)),
                ('tabele_no', models.CharField(max_length=100, null=True)),
                ('ip', models.CharField(max_length=100, null=True)),
                ('port', models.IntegerField(null=True)),
                ('food_delivered', models.BooleanField(default=False)),
                ('food_type', models.CharField(choices=[('solid', 'solid'), ('liquid', 'liquid')], default='solid', max_length=100)),
                ('speed', models.IntegerField(choices=[(120, 120), (90, 90)], default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Temporary Delivery',
                'verbose_name_plural': 'Temporary Delliveries',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.CharField(max_length=20, unique=True)),
                ('avialable', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.restaurant')),
            ],
            options={
                'verbose_name': 'Tables',
                'ordering': ('-id',),
            },
        ),
    ]
