# Generated by Django 3.1.4 on 2021-11-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0002_auto_20211125_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='food_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='ip',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='port',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='speed_of_the_bot',
            field=models.IntegerField(null=True),
        ),
    ]
