# Generated by Django 3.1.4 on 2021-11-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0003_auto_20211125_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempdelivery',
            old_name='tabele_no',
            new_name='table_no',
        ),
    ]
