# Generated by Django 3.1.4 on 2021-11-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0004_auto_20211125_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdelivery',
            name='bot_id',
            field=models.IntegerField(null=True),
        ),
    ]
