# Generated by Django 3.1.4 on 2021-11-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0005_tempdelivery_bot_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='bot_no',
            new_name='bot_id',
        ),
    ]
