# Generated by Django 3.1.4 on 2021-11-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0006_auto_20211125_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='bot_color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tempdelivery',
            name='bot_color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
