# Generated by Django 3.1.4 on 2021-12-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0007_auto_20211125_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ('table_no',), 'verbose_name': 'Tables'},
        ),
    ]
